const discoverTab = [
    {
        name: 'Comps',
        desc: 'The comps page is even better in the app. On top of the usual data, it gives you early game boards to aim for, and warns you which comps are likely to be contested in your lobby based on the match history of your opponents. Using the app helps us to improve our data too!',
        img: 'https://cdn.metatft.com/file/metatft/app/comps_710.png',
        urldesc: '',
        url: '/comps',
    },
    {
        name: 'Lobby Scouting',
        desc: 'When you load into game, we quickly analyse every player in your lobby and give them tags so that you know who to watch out for, and how stacked your game is.',
        img: 'https://cdn.metatft.com/file/metatft/app/Scouting_710.png',
        urldesc: '',
        url: '/comps',
    },
    {
        name: 'Loaded Dice',
        desc: "Are you using your Loaded Dice optimally? We've calculated all the possibile outcomes of using your loaded dice on each unit - If you know what unit you want, quickly look up the highest probability units to dice.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Loadeddice.PNG',
        urldesc: 'Find the best units to use your dice on...',
        url: '/download',
    },
    {
        name: 'Augments',
        desc: "Introduced in Set 6, Augments impact your game in unique ways. Look up the best Augments, filter by when they're offered (1st/2nd/3rd) or what tier they are, and quickly search for the best ones you're offered.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Augments.PNG',
        urldesc: 'Compare and search Augment stats...',
        url: '/download',
    },
    {
        name: 'Items',
        desc: "A tier list for the best items in TFT. Select a unit to discover the best items for that unit, best in slot builds, as well as more data and stats on that unit's performance.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Items.PNG',
        urldesc: 'Discover the best items in TFT...',
        url: '/comps',
    },
    {
        name: 'Champs',
        desc: 'A tier list of the best performing TFT Champions. You can also filter by an item, giving you a list of the best units with a given item, as well as more stats about that item',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Units.PNG',
        urldesc: 'Compare the performance of TFT champions...',
        url: '/comps',
    },
    {
        name: 'Triats',
        desc: 'The performance of different Trait options, laid out in a simple list. Compare average placement, frequency and win-rate of TFT Trait bonuses.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Traits.PNG',
        urldesc: 'Analyse the best Traits to run...',
        url: '/download',
    },
    {
        name: 'Rasing',
        desc: 'Every day, we scan the TFT leaderboards and highlight the fastest climbing players in each region. Discover what the top players are running, uncover their playstyles and learn from the best.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Rising.PNG',
        urldesc: 'See what the best players are up to...',
        url: '/download',
    },
    {
        name: 'In-game App',
        desc: 'Want all of these features and more, directly in your game? Check out our free in-game app on Overwolf - includes matchup tracking, player tags, round by round match history, comps overlay and more.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/App.PNG',
        urldesc: 'Learn more...',
        url: '/download',
    },
];

const discoverMetaTFT = [
    {
        name: 'Comps',
        desc: 'The comps page calculates average placement and pick rate for the current top meta TFT comps. Filters let you customise the page for your rank and region, and you can expand each comp for extra data, including different comp options, positioning examples, and best augments.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Comps.PNG',
        urldesc: 'Check out the top performing comps in the current meta...',
        url: '/comps',
    },
    {
        name: 'Game Modes',
        desc: "Hyper Roll and Double Up game modes have different pacing, and so the meta can be very unlike regular ranked TFT. Thats why we've calculated the top comps for each game mode by exclusively looking at data from those games.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Hyperroll.PNG',
        urldesc: 'See the best comps for Hyper Roll... Or the best comps for Double Up...',
        url: '/comps',
    },
    {
        name: 'Loaded Dice',
        desc: "Are you using your Loaded Dice optimally? We've calculated all the possibile outcomes of using your loaded dice on each unit - If you know what unit you want, quickly look up the highest probability units to dice.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Loadeddice.PNG',
        urldesc: 'Find the best units to use your dice on...',
        url: '/download',
    },
    {
        name: 'Augments',
        desc: "Introduced in Set 6, Augments impact your game in unique ways. Look up the best Augments, filter by when they're offered (1st/2nd/3rd) or what tier they are, and quickly search for the best ones you're offered.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Augments.PNG',
        urldesc: 'Compare and search Augment stats...',
        url: '/download',
    },
    {
        name: 'Items',
        desc: "A tier list for the best items in TFT. Select a unit to discover the best items for that unit, best in slot builds, as well as more data and stats on that unit's performance.",
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Items.PNG',
        urldesc: 'Discover the best items in TFT...',
        url: '/comps',
    },
    {
        name: 'Champs',
        desc: 'A tier list of the best performing TFT Champions. You can also filter by an item, giving you a list of the best units with a given item, as well as more stats about that item',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Units.PNG',
        urldesc: 'Compare the performance of TFT champions...',
        url: '/comps',
    },
    {
        name: 'Triats',
        desc: 'The performance of different Trait options, laid out in a simple list. Compare average placement, frequency and win-rate of TFT Trait bonuses.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Traits.PNG',
        urldesc: 'Analyse the best Traits to run...',
        url: '/download',
    },
    {
        name: 'Rasing',
        desc: 'Every day, we scan the TFT leaderboards and highlight the fastest climbing players in each region. Discover what the top players are running, uncover their playstyles and learn from the best.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/Rising.PNG',
        urldesc: 'See what the best players are up to...',
        url: '/download',
    },
    {
        name: 'In-game App',
        desc: 'Want all of these features and more, directly in your game? Check out our free in-game app on Overwolf - includes matchup tracking, player tags, round by round match history, comps overlay and more.',
        img: 'https://www.metatft.com/cdn-cgi/image/width=710,format=auto/https://cdn.metatft.com/file/metatft/set8/images/App.PNG',
        urldesc: 'Learn more...',
        url: '/download',
    },
];

export { discoverTab, discoverMetaTFT };
